"""empty message

Revision ID: eb220b762662
Revises: 
Create Date: 2022-03-01 13:26:36.927122

"""
from alembic import op
import sqlalchemy as sa
import depot


# revision identifiers, used by Alembic.
revision = 'eb220b762662'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'image',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('file', depot.fields.sqlalchemy.UploadedFileField(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=True)
    op.create_table(
        'product',
        sa.Column('id', sa.String(length=355), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('logo_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['logo_id'], ['image.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    op.create_table(
        'ProductImages',
        sa.Column('id', sa.String(length=355), nullable=True),
        sa.Column('image_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['product.id'], ),
        sa.ForeignKeyConstraint(['image_id'], ['image.id'], )
    )
    op.create_table(
        'variant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.String(length=355), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('size', sa.String(length=50), nullable=True),
        sa.Column('color', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('logo_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['logo_id'], ['image.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_id'), 'variant', ['id'], unique=True)
    op.create_table(
        'VariantImages',
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('image_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['id'], ['variant.id'], ),
        sa.ForeignKeyConstraint(['image_id'], ['image.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VariantImages')
    op.drop_index(op.f('ix_variant_id'), table_name='variant')
    op.drop_table('variant')
    op.drop_table('ProductImages')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
